name: 'Configuration selector'
type: module
description: 'A utility module that enables different versions of optional configuration to be selected on module install.'
# core: 8.x

# Information added by Drupal.org packaging script on 2018-05-07
version: '8.x-1.0-alpha4'
core: '8.x'
project: 'config_selector'
datestamp: 1525693426
